import { SceneDefinition, PresetValues, PresenterPreset } from './types';

export const PRESENTATION_SCENES: SceneDefinition[] = [
  {
    id: 'INTRO',
    index: 0,
    chapterNumber: '00',
    chapterTitle: 'DEEP SEA OPERATION',
    sceneTitle: 'DEEP SEA COMMERCIAL VOYAGE',
    sceneSubtitle: 'Panamax Bulk Carrier at Sea — Telemetry & Fuel Consumption',
    sectionIdInExploreMode: 'intro',
    keyHighlight: {
      label: 'ANNUAL FUEL BURN',
      value: '10,000 MT',
      sublabel: '₹50.0 Cr/yr bunker drainage',
    },
  },
  {
    id: 'PROBLEM',
    index: 1,
    chapterNumber: '01',
    chapterTitle: 'THE PROBLEM',
    sceneTitle: 'SHIPPING HAS A GREEN CAPITAL BOTTLENECK',
    sceneSubtitle: 'Three structural impasses preventing retrofit adoption at scale',
    sectionIdInExploreMode: 'problem',
    keyHighlight: {
      label: 'UPFRONT CAPEX IMPASSE',
      value: '₹8 – 20 Cr ($1.0M – $2.4M USD)',
      sublabel: 'Locked balance sheets',
    },
  },
  {
    id: 'INSIGHT',
    index: 2,
    chapterNumber: '02',
    chapterTitle: 'THE INSIGHT',
    sceneTitle: 'WHAT IF SAVINGS WERE THE AMORTIZATION?',
    sceneSubtitle: 'Turning future fuel reductions into bankable debt security',
    sectionIdInExploreMode: 'insight',
    keyHighlight: {
      label: 'EQUITY REQUIRED',
      value: '₹0.00 Cr',
      sublabel: '100% savings-backed SPV',
    },
  },
  {
    id: 'ENGINE',
    index: 3,
    chapterNumber: '03',
    chapterTitle: 'THE SHIPLOOP MODEL',
    sceneTitle: 'THE SHIPLOOP CLOSED-LOOP ENGINE',
    sceneSubtitle: '6-step protocol linking capital directly to physical bunker reductions',
    sectionIdInExploreMode: 'engine',
    keyHighlight: {
      label: 'MECHANISM',
      value: 'CLOSED LOOP',
      sublabel: 'Automated escrow repayment',
    },
  },
  {
    id: 'SIMULATOR',
    index: 4,
    chapterNumber: '04',
    chapterTitle: 'THE FINANCIAL ENGINE',
    sceneTitle: 'LIVE UNDERWRITING & VESSEL SIMULATOR',
    sceneSubtitle: 'Real-time financial calculus with instant preset scenario benchmarking',
    sectionIdInExploreMode: 'simulator',
    keyHighlight: {
      label: 'ANNUAL SAVINGS',
      value: '₹7.50 Cr',
      sublabel: 'DSCR 3.44x coverage',
    },
  },
  {
    id: 'WATERFALL',
    index: 5,
    chapterNumber: '05',
    chapterTitle: 'CAPITAL WATERFALL',
    sceneTitle: 'ANNUAL SAVINGS DISTRIBUTION WATERFALL',
    sceneSubtitle: 'Fair distribution: Senior Debt, Platform Oracle, Charterer, and Owner',
    sectionIdInExploreMode: 'waterfall',
    keyHighlight: {
      label: 'FREE CASHFLOW',
      value: '+₹5.02 Cr',
      sublabel: 'Split between Owner & Charterer',
    },
  },
  {
    id: 'CHARTER',
    index: 6,
    chapterNumber: '06',
    chapterTitle: 'CONTRACTUAL ARCHITECTURE',
    sceneTitle: 'SOLVING THE SPLIT INCENTIVE (VOYAGE VS TIME CHARTER)',
    sceneSubtitle: 'BIMCO transition clause sharing verified savings between owner & charterer',
    sectionIdInExploreMode: 'charter',
    keyHighlight: {
      label: 'SPLIT INCENTIVE',
      value: 'RESOLVED',
      sublabel: '50/50 shared surplus',
    },
  },
  {
    id: 'VERIFICATION',
    index: 7,
    chapterNumber: '07',
    chapterTitle: 'CLASS ORACLE',
    sceneTitle: 'SENSOR FUSION & THE CLASS ORACLE',
    sceneSubtitle: 'De-risking institutional debt with continuous high-frequency telemetry',
    sectionIdInExploreMode: 'verification',
    keyHighlight: {
      label: 'ORACLE TRUST',
      value: 'CRYPTOGRAPHIC',
      sublabel: 'DNV / Bureau Veritas audited',
    },
  },
  {
    id: 'FEET',
    index: 8,
    chapterNumber: '08',
    chapterTitle: 'FEET BENCHMARK',
    sceneTitle: 'THE MODEL ALREADY EXISTS.',
    sceneSubtitle: "FEET demonstrates that future fuel savings can be used to finance today's maritime retrofit.",
    sectionIdInExploreMode: 'feet',
    keyHighlight: {
      label: 'REAL-WORLD BENCHMARK',
      value: 'UP TO $35M',
      sublabel: '100% upfront pay-as-you-save',
    },
  },
  {
    id: 'RISK',
    index: 9,
    chapterNumber: '09',
    chapterTitle: 'RISK DEFENSE',
    sceneTitle: 'DEFENSIVE PROTOCOL & STRESS TESTING',
    sceneSubtitle: 'Testing volatility: Bunker price collapse, off-hire, and tech underperformance',
    sectionIdInExploreMode: 'risk',
    keyHighlight: {
      label: 'DEFENSE SHIELD',
      value: '6-MO DSRF',
      sublabel: 'Debt service reserve fund',
    },
  },
  {
    id: 'INDIA',
    index: 10,
    chapterNumber: '10',
    chapterTitle: 'INDIA DEPLOYMENT',
    sceneTitle: 'FROM GLOBAL PROOF TO INDIAN DEPLOYMENT',
    sceneSubtitle: "SHIPLOOP adapts the pay-as-you-save retrofit model to India's maritime, banking and green-finance ecosystem.",
    sectionIdInExploreMode: 'india',
    keyHighlight: {
      label: 'PROPOSED ARCHITECTURE',
      value: 'PAY-AS-YOU-SAVE',
      sublabel: 'Green finance window integration',
    },
  },
  {
    id: 'SCALE',
    index: 11,
    chapterNumber: '11',
    chapterTitle: 'THE FUTURE',
    sceneTitle: 'FLEET SCALE MULTIPLIER: 1 → 1,000 VESSELS',
    sceneSubtitle: 'From single pilot vessel to institutional green maritime securitization',
    sectionIdInExploreMode: 'scale',
    keyHighlight: {
      label: 'FLEET TARGET',
      value: '1,000 SHIPS',
      sublabel: '₹7,500 Cr/yr national bunker saved',
    },
  },
  {
    id: 'CONCLUSION',
    index: 12,
    chapterNumber: '12',
    chapterTitle: 'CONCLUSION',
    sceneTitle: 'THE VERDICT: ZERO-EQUITY DECARBONIZATION',
    sceneSubtitle: 'A quadruple-win for Lenders, Shipowners, Charterers, and the Planet',
    sectionIdInExploreMode: 'aha-cta',
    keyHighlight: {
      label: 'CAPITAL EFFICIENCY',
      value: 'ZERO EQUITIES',
      sublabel: 'Self-amortizing green infrastructure',
    },
  },
];

export const PRESENTER_PRESETS: Record<PresenterPreset, PresetValues> = {
  BASE: {
    name: 'BASE CASE',
    tag: 'STANDARD MARITIME ASSUMPTIONS',
    efficiency: 15.0,
    fuelPrice: 50000,
    operatingDays: 300,
    retrofitCost: 10.0,
    description: '15% efficiency improvement, ₹50,000/t VLSFO bunker, 300 sailing days/yr (100% target utilization).',
  },
  OPTIMISTIC: {
    name: 'OPTIMISTIC',
    tag: 'HIGH BUNKER & FULL COMPLIANCE',
    efficiency: 22.0,
    fuelPrice: 62000,
    operatingDays: 340,
    retrofitCost: 10.0,
    description: '22% efficiency (wind-assist + air lubrication combo), ₹62,000/t high bunker prices, 340 sea days.',
  },
  CONSERVATIVE: {
    name: 'CONSERVATIVE',
    tag: 'MODERATE WEATHER & 80% UTILIZATION',
    efficiency: 8.0,
    fuelPrice: 40000,
    operatingDays: 240,
    retrofitCost: 10.0,
    description: '8% modest hydrodynamic gain, ₹40,000/t low fuel market, 240 sea days (80% utilization).',
  },
  STRESS: {
    name: 'STRESS CASE',
    tag: 'CRASHED BUNKER & 60% UTILIZATION',
    efficiency: 5.0,
    fuelPrice: 35000,
    operatingDays: 180,
    retrofitCost: 10.0,
    description: '5% minimal efficiency gain, ₹35,000/t crashed bunker price, 180 days (60% utilization / long port idle).',
  },
};
