export type FeetDataStatus = 
  | 'VERIFIED'
  | 'REAL-WORLD DATA'
  | 'VERIFIED PILOT DATA'
  | 'CONTEXTUAL MARKET DATA'
  | 'TARGET'
  | 'PROPOSED'
  | 'SIMULATION';

export interface FeetMetricRecord {
  id: string; // e.g. FEET-001
  metric: string;
  value: string;
  unit: string;
  displayValue: string;
  description: string;
  status: FeetDataStatus;
  statusBadge: string;
  sourceName: string;
  sourceUrl: string;
  confidenceInterval?: string;
  notes?: string;
}

export interface ComparisonDimension {
  id: string;
  number: string;
  title: string;
  feet: {
    title: string;
    description: string;
    status: FeetDataStatus;
    statusBadge: string;
    tag: string;
  };
  shiploop: {
    title: string;
    description: string;
    status: FeetDataStatus;
    statusBadge: string;
    verb: 'EXTENDS' | 'ADAPTS' | 'DEPLOYS' | 'LOCALIZES' | 'BUILDS ON';
  };
}

export interface ShiploopAdditionLayer {
  number: string;
  title: string;
  headline: string;
  description: string;
  badge: string;
  deliverables: string[];
}

// Central verified FEET benchmark metrics & research data
export const FEET_DATA_RECORDS: FeetMetricRecord[] = [
  {
    id: 'FEET-001',
    metric: 'INITIAL CLOSING FACILITY',
    value: '35',
    unit: 'USD Millions',
    displayValue: 'UP TO $35M',
    description: 'Initial commercial closing capital dedicated to maritime energy efficiency technology (EET) retrofit facilities.',
    status: 'VERIFIED',
    statusBadge: 'VERIFIED / REAL-WORLD DATA',
    sourceName: 'Fund for Energy Efficiency Technologies (FEET) Facility Launch Documentation',
    sourceUrl: 'SOURCE LINK PENDING',
    notes: 'Real-world commercial closing proving institutional capital appetite for maritime pay-as-you-save retrofits.'
  },
  {
    id: 'FEET-002',
    metric: 'UPFRONT FINANCING COVERAGE',
    value: '100',
    unit: '%',
    displayValue: 'UP TO 100%',
    description: 'Full capex coverage of qualified energy-saving technologies and drydock installation, removing balance sheet friction for shipowners.',
    status: 'VERIFIED',
    statusBadge: 'VERIFIED',
    sourceName: 'FEET Financing Facility Term Sheet & Program Guidelines',
    sourceUrl: 'SOURCE LINK PENDING',
    notes: 'Eliminates upfront capex constraint that previously blocked 60%+ of commercial retrofit decisions.'
  },
  {
    id: 'FEET-003',
    metric: 'REPAYMENT MECHANISM',
    value: 'Pay-As-You-Save',
    unit: 'Mechanism',
    displayValue: 'PAY-AS-YOU-SAVE',
    description: 'Debt amortization linked directly to verified fuel reductions and operational carbon savings generated by retrofits.',
    status: 'VERIFIED',
    statusBadge: 'VERIFIED',
    sourceName: 'FEET Operational Framework & Pay-As-You-Save Protocol',
    sourceUrl: 'SOURCE LINK PENDING',
    notes: 'Vessel pays out of realized operational cashflow savings rather than fixed unhedged debt service.'
  },
  {
    id: 'FEET-004',
    metric: 'CONTRACTUAL & LEGAL STRUCTURE',
    value: 'Unsecured Leases',
    unit: 'Legal Structure',
    displayValue: 'UNSECURED LEASES',
    description: 'Off-balance sheet unsecured operating lease structure used to decouple retrofit financing from preexisting first-priority vessel mortgages.',
    status: 'VERIFIED',
    statusBadge: 'VERIFIED',
    sourceName: 'FEET Legal & Inter-creditor Structuring Memorandum',
    sourceUrl: 'SOURCE LINK PENDING',
    notes: 'Avoids subordination disputes with senior mortgage lenders who already hold first preferred ship mortgages.'
  },
  {
    id: 'FEET-005',
    metric: '2030 EXPANSION TARGET',
    value: '500',
    unit: 'USD Millions',
    displayValue: 'USD 500M',
    description: 'Targeted long-term expansion pipeline aiming to aggregate and mobilize $500 million in blended retrofit capital by 2030.',
    status: 'TARGET',
    statusBadge: 'TARGET',
    sourceName: 'FEET 2030 Scaling Roadmap & Blended Finance Working Group',
    sourceUrl: 'SOURCE LINK PENDING',
    notes: 'Target projection; not an achieved result. Demonstrates institutional vision for industrial maritime scale.'
  },
  {
    id: 'FEET-006',
    metric: 'MEAN INSTANTANEOUS POWER SAVINGS',
    value: '7.2',
    unit: '%',
    displayValue: '7.2%',
    confidenceInterval: '6.2% — 8.2%',
    description: 'Illustrative empirical evidence from a monitored oil-tanker retrofit pilot demonstrating verified shaft power reduction under operational conditions.',
    status: 'VERIFIED PILOT DATA',
    statusBadge: 'VERIFIED PILOT DATA',
    sourceName: 'Monitored Oil-Tanker Energy Efficiency Retrofit Pilot Study',
    sourceUrl: 'SOURCE LINK PENDING',
    notes: 'Observed mean savings of 7.2% with a 95% confidence interval of 6.2% to 8.2%. Does not imply 7.2% applies universally to all vessels or technologies.'
  },
  {
    id: 'FEET-007',
    metric: 'GLOBAL MARITIME ADOPTION GAP',
    value: '270',
    unit: 'of ~60,000 Vessels (<0.5%)',
    displayValue: '270 / 60,000 (< 0.5%)',
    description: 'Approximately 270 of ~60,000 vessels discussed in GCMD context as having selected energy-efficiency technologies (such as wind-assisted propulsion or air lubrication), illustrating the massive gap between available efficiency technologies and adoption.',
    status: 'CONTEXTUAL MARKET DATA',
    statusBadge: 'CONTEXTUAL MARKET DATA',
    sourceName: 'Global Centre for Maritime Decarbonisation (GCMD) Industry Context Report',
    sourceUrl: 'SOURCE LINK PENDING',
    notes: 'Under 0.5% adoption confirms that technology exists and works, but market financing and deployment rails remain the limiting constraint.'
  },
  {
    id: 'FEET-008',
    metric: '2030 TARGET FLEET COHORT',
    value: '200',
    unit: 'Commercial Vessels',
    displayValue: '~200 SHIPS',
    description: 'Approximate target fleet size corresponding to the $500M 2030 expansion vision.',
    status: 'TARGET',
    statusBadge: 'TARGET',
    sourceName: 'FEET 2030 Strategic Scaling Outline',
    sourceUrl: 'SOURCE LINK PENDING',
    notes: 'Target indicator; serves as benchmark for fleet-level scale modeling.'
  }
];

// Helper to lookup record by ID
export const getFeetRecord = (id: string): FeetMetricRecord | undefined => {
  return FEET_DATA_RECORDS.find(r => r.id === id);
};

// 10 Comparative Dimensions between FEET (Real-World Benchmark) and SHIPLOOP (Proposed India Deployment)
export const COMPARISON_DIMENSIONS: ComparisonDimension[] = [
  {
    id: 'dim-core-mechanism',
    number: '01',
    title: 'CORE MECHANISM',
    feet: {
      title: 'Pay-as-you-save retrofit financing',
      description: 'Capital is recouped from verified operational fuel savings over time.',
      status: 'VERIFIED',
      statusBadge: 'VERIFIED',
      tag: 'REAL-WORLD BENCHMARK',
    },
    shiploop: {
      title: 'Pay-as-you-save retrofit financing + India deployment layer',
      description: 'Adopts the proven pay-as-you-save core, wrapping it in localized Indian banking, shipyard, and port operational workflows.',
      status: 'PROPOSED',
      statusBadge: 'PROPOSED',
      verb: 'EXTENDS',
    },
  },
  {
    id: 'dim-upfront-financing',
    number: '02',
    title: 'UPFRONT FINANCING',
    feet: {
      title: 'Up to 100%',
      description: 'Eliminates initial capital expenditure for qualified retrofit installations.',
      status: 'VERIFIED',
      statusBadge: 'VERIFIED',
      tag: 'REAL-WORLD BENCHMARK',
    },
    shiploop: {
      title: 'Configurable financing structure (100% baseline modeled)',
      description: 'Simulates 70%–100% debt tranches aligned with domestic green financing windows and senior lender risk appetites.',
      status: 'PROPOSED',
      statusBadge: 'PROPOSED',
      verb: 'BUILDS ON',
    },
  },
  {
    id: 'dim-repayment-basis',
    number: '03',
    title: 'REPAYMENT BASIS',
    feet: {
      title: 'Verified fuel and regulatory savings',
      description: 'Cashflow deductions pegged to measured fuel and carbon compliance savings.',
      status: 'VERIFIED',
      statusBadge: 'VERIFIED',
      tag: 'REAL-WORLD BENCHMARK',
    },
    shiploop: {
      title: 'Verified operational savings feeding structured repayment',
      description: 'Continuous noon-report & sensor telemetry stream calculates verifiable INR cashflow for automated escrow distribution.',
      status: 'PROPOSED',
      statusBadge: 'PROPOSED',
      verb: 'LOCALIZES',
    },
  },
  {
    id: 'dim-verification',
    number: '04',
    title: 'SAVINGS VERIFICATION',
    feet: {
      title: 'Savings verification built into financing mechanism',
      description: 'Integrated verification methodology to confirm operational baseline and post-retrofit deltas.',
      status: 'VERIFIED',
      statusBadge: 'VERIFIED',
      tag: 'REAL-WORLD BENCHMARK',
    },
    shiploop: {
      title: 'Proposed independent verification + class oracle data layer',
      description: 'Architects multi-tiered telemetry ingestion (ISO 19030 / ITTC guidelines) audited by Classification Societies (IRS, DNV).',
      status: 'PROPOSED',
      statusBadge: 'PROPOSED',
      verb: 'EXTENDS',
    },
  },
  {
    id: 'dim-financing-structure',
    number: '05',
    title: 'FINANCING STRUCTURE',
    feet: {
      title: 'Unsecured lease structure',
      description: 'Decoupled from primary ship mortgages to avoid inter-creditor gridlock.',
      status: 'VERIFIED',
      statusBadge: 'VERIFIED',
      tag: 'REAL-WORLD BENCHMARK',
    },
    shiploop: {
      title: 'Proposed Indian bank / green-finance structure',
      description: 'Proposes bankruptcy-remote project SPVs, escrow waterfalls, and credit enhancement via DSRF and credit insurance.',
      status: 'PROPOSED',
      statusBadge: 'PROPOSED',
      verb: 'ADAPTS',
    },
  },
  {
    id: 'dim-geography',
    number: '06',
    title: 'GEOGRAPHIC SCOPE',
    feet: {
      title: 'Global maritime financing initiative',
      description: 'International deep-sea merchant trade lanes across multinational jurisdictions.',
      status: 'REAL-WORLD DATA',
      statusBadge: 'REAL-WORLD DATA',
      tag: 'REAL-WORLD BENCHMARK',
    },
    shiploop: {
      title: 'India-focused deployment concept',
      description: 'Tailored for Indian coastal shipping corridors (SagarMala), major port trusts (JNPT, Mundra, Cochin), and domestic yards (CSL).',
      status: 'PROPOSED',
      statusBadge: 'PROPOSED',
      verb: 'LOCALIZES',
    },
  },
  {
    id: 'dim-banking-integration',
    number: '07',
    title: 'BANKING INTEGRATION',
    feet: {
      title: 'Fund / financing partners',
      description: 'Specialized blended finance facilities and international commercial fund partners.',
      status: 'REAL-WORLD DATA',
      statusBadge: 'REAL-WORLD DATA',
      tag: 'REAL-WORLD BENCHMARK',
    },
    shiploop: {
      title: 'Proposed integration with Indian financial institutions',
      description: 'Proposes green lending interfaces for Indian public sector and commercial banks (SBI, IREDA, EXIM Bank of India).',
      status: 'PROPOSED',
      statusBadge: 'PROPOSED',
      verb: 'DEPLOYS',
    },
  },
  {
    id: 'dim-policy-integration',
    number: '08',
    title: 'POLICY INTEGRATION',
    feet: {
      title: 'Global maritime decarbonisation context',
      description: 'Aligned with IMO GHG targets, Carbon Intensity Indicator (CII), and European ETS mandates.',
      status: 'REAL-WORLD DATA',
      statusBadge: 'REAL-WORLD DATA',
      tag: 'REAL-WORLD BENCHMARK',
    },
    shiploop: {
      title: 'Proposed alignment with India\'s green-shipping / green-finance ecosystem',
      description: 'Aligns directly with Maritime India Vision 2030, Harit Nauka Guidelines, and National Green Shipping initiatives.',
      status: 'PROPOSED',
      statusBadge: 'PROPOSED',
      verb: 'LOCALIZES',
    },
  },
  {
    id: 'dim-data-platform',
    number: '09',
    title: 'DATA PLATFORM & SIMULATION',
    feet: {
      title: 'Financing + verification mechanism',
      description: 'Transactional contracting, baseline performance auditing, and repayment settlement.',
      status: 'REAL-WORLD DATA',
      statusBadge: 'REAL-WORLD DATA',
      tag: 'REAL-WORLD BENCHMARK',
    },
    shiploop: {
      title: 'Financing + verification + simulation + monitoring platform',
      description: 'Interactive software cockpit providing live financial underwriting, cashflow distribution waterfalls, and scenario stress testing.',
      status: 'PROPOSED',
      statusBadge: 'PROPOSED',
      verb: 'EXTENDS',
    },
  },
  {
    id: 'dim-charter-structure',
    number: '10',
    title: 'CHARTER STRUCTURE & SPLIT INCENTIVE',
    feet: {
      title: 'Address split incentives through financing mechanism',
      description: 'Structures lease repayments to balance fuel bill payer and asset owner economics.',
      status: 'VERIFIED',
      statusBadge: 'VERIFIED',
      tag: 'REAL-WORLD BENCHMARK',
    },
    shiploop: {
      title: 'Explicit voyage/time-charter logic + proposed savings-sharing structure',
      description: 'Integrates BIMCO transition clauses with configurable charterer savings-sharing slider (0%–100%) and dual-surplus accounting.',
      status: 'PROPOSED',
      statusBadge: 'PROPOSED',
      verb: 'BUILDS ON',
    },
  },
];

// The 5 Layers of "THE SHIPLOOP ADDITION"
export const SHIPLOOP_ADDITION_LAYERS: ShiploopAdditionLayer[] = [
  {
    number: '01',
    title: 'INDIA DEPLOYMENT',
    headline: 'Localized Maritime Corridors & Shipyards',
    description: 'Anchors the pay-as-you-save model into domestic coastal shipping hubs (JNPT, Mundra, Cochin) and public/private ship repair facilities (CSL, L&T).',
    badge: 'PROPOSED ARCHITECTURE',
    deliverables: [
      'Coastal vessel clustering around major Indian ports',
      'Integration with domestic drydock scheduling and yard capacities',
      'Alignment with Maritime India Vision 2030 decarbonization goals'
    ]
  },
  {
    number: '02',
    title: 'BANKING WORKFLOW',
    headline: 'Domestic Green Debt & Escrow Protocol',
    description: 'Proposes standard underwriting templates and bankruptcy-remote SPV structures tailored for Indian public banks (SBI, IREDA, Bank of Baroda).',
    badge: 'PROPOSED ARCHITECTURE',
    deliverables: [
      'Debt Service Reserve Fund (6-month DSRF) buffer sizing',
      'Automated waterfall escrow account routing',
      'First-loss mezzanine credit enhancement concepts'
    ]
  },
  {
    number: '03',
    title: 'LIVE FINANCIAL SIMULATION',
    headline: 'Dynamic Real-Time Underwriting Engine',
    description: 'Provides live sensitivity modeling across fuel pricing, operating days, retrofit Capex, efficiency gains, and DSCR coverage multiples.',
    badge: 'INTERACTIVE MODEL',
    deliverables: [
      'Instant DSCR, NPV, and payback period calculation',
      'Real-time waterfall split between debt, owner, and charterer',
      'One-click scenario benchmarking (Base, Optimistic, Conservative, Stress)'
    ]
  },
  {
    number: '04',
    title: 'RISK / STRESS TESTING',
    headline: 'Multi-Factor Defensive Risk Terminal',
    description: 'Live stress-testing against bunker price collapse (-30%), long port idle/off-hire, and technology performance underdelivery.',
    badge: 'DEFENSIVE LAB',
    deliverables: [
      'Automated shortfall mitigation protocol activation',
      'DSRF reserve depletion and replenishment tracking',
      'Breakeven bunker price and minimum operating day limits'
    ]
  },
  {
    number: '05',
    title: 'PRESENTER-READY EVIDENCE LAYER',
    headline: 'Structured Verification & Citation Pipeline',
    description: 'Every assumption, regulatory citation, and performance metric is linked to auditable source references and verifiable pilot bounds.',
    badge: 'EVIDENCE LINK READY',
    deliverables: [
      'Auditable citation records (IMO GHG4, GCMD, BIMCO, FEET)',
      'Clear differentiation: [VERIFIED], [TARGET], [PROPOSED], [SIMULATION]',
      'Direct link-ready architecture for independent maritime class oracles'
    ]
  }
];

// The 6-step FEET Mechanism Flow
export const FEET_MECHANISM_STEPS = [
  {
    step: '01',
    label: 'CAPITAL',
    title: 'Upfront Capital Facility',
    detail: 'Up to 100% upfront financing funded through specialized blended debt, avoiding owner balance sheet equity drain.',
    verified: true,
  },
  {
    step: '02',
    label: 'RETROFIT',
    title: 'Technology Installation',
    detail: 'Energy-efficiency technologies (air lubrication, wind-assist, hull coatings, Mewis ducts) installed during scheduled drydock.',
    verified: true,
  },
  {
    step: '03',
    label: 'FUEL / REGULATORY SAVINGS',
    title: 'Fuel & Carbon Reductions',
    detail: 'Immediate reduction in daily fuel burn and EU ETS / IMO CII carbon compliance penalties at sea.',
    verified: true,
  },
  {
    step: '04',
    label: 'VERIFICATION',
    title: 'Independent Performance Audit',
    detail: 'High-frequency continuous telemetry and noon-reports verified against operational baseline to quantify genuine savings.',
    verified: true,
  },
  {
    step: '05',
    label: 'PAY-AS-YOU-SAVE REPAYMENT',
    title: 'Cashflow-Linked Amortization',
    detail: 'Repayment stream deducted from realized fuel savings, ensuring vessel generates surplus cashflow above debt service.',
    verified: true,
  },
  {
    step: '06',
    label: 'FINANCING RECOVERED',
    title: 'Capital Recovered & Retained Upside',
    detail: 'Lender capital fully recovered over agreed term; 100% of post-amortization efficiency gains remain with the shipowner.',
    verified: true,
  }
];
